# Generated by Django 4.1.2 on 2022-11-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="profile_pic",
            field=models.ImageField(
                default="",
                upload_to="C:\\Users\\DELL\\Desktop\\Yash coding exercies\\blog\\jigyaasa\\static",
            ),
        ),
    ]
