# Generated by Django 4.1.2 on 2022-11-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_upload_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="profile_pic",
            field=models.ImageField(upload_to="image"),
        ),
    ]
