# Generated by Django 4.1.2 on 2022-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_upload_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="post", name="likes", field=models.IntegerField(default=0),
        ),
    ]
