# Generated by Django 4.1.2 on 2022-11-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_post_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="likes",),
    ]
